name: build_docs_requirements_file

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build_docs_requirements_file:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      # Used to host build wheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install Docs
      - name: Install Build
        run: pip install .[docs]

      # Build requirements
      - name: Build doc requirements
        run: |
          # Compile requirements
          toml-to-req \
            --toml-file pyproject.toml \
            --optional-lists docs \
            --requirements-file docs/requirements.txt

      # Commit
      - uses: endbug/add-and-commit@v9
        with:
          add: 'docs/requirements.txt'
          default_author: github_actions
          message: 'docs: Update requirements'
          push: true
